# Generated by Django 3.0.6 on 2020-05-18 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='taskicons/')),
                ('trialinfo', models.FileField(upload_to='json/')),
                ('experimenter', models.OneToOneField(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
