# Generated by Django 3.0.7 on 2020-06-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_url',
            field=models.CharField(default='VwI6g70Eqx4zfrwlngpSIvu8cITQQFtckyHA5_W_XPc', max_length=32, unique=True),
        ),
    ]
