# Generated by Django 3.0.7 on 2020-06-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_url',
            field=models.CharField(default='N43Hi73_OF4pA68WwqsH58OWKiKrUVkujyHwgLQjiN0', max_length=32, unique=True),
        ),
    ]
