# Generated by Django 3.0.6 on 2020-05-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='displayname',
            field=models.CharField(default='', help_text='Human-friendly name for the task', max_length=80),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Short codename for task', max_length=24, primary_key=True, serialize=False),
        ),
    ]
