# Generated by Django 3.0.7 on 2020-06-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200616_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_url',
            field=models.CharField(default='P1ZDQe-kvSnHhChNMrL61iglstHWrgO9yoTGd6Xj2fI', max_length=32, unique=True),
        ),
    ]
