# Generated by Django 3.0.6 on 2020-05-18 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20200518_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='experimenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Trial3AFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus', models.URLField()),
                ('answer', models.PositiveSmallIntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Response3AFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Trial3AFC')),
            ],
        ),
    ]
