# Generated by Django 3.0.6 on 2020-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200525_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='descr',
            field=models.TextField(default='', help_text='Please provide a one-sentence description', verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='displayname',
            field=models.CharField(default='', help_text='Human-friendly name for the task to be for display', max_length=80, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Short codename for task', max_length=24, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='trialinfo',
            field=models.FileField(help_text='JSON file with task information', upload_to='json/', verbose_name='Trial Info'),
        ),
    ]
