# Generated by Django 3.0.7 on 2020-06-16 17:08

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200616_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_url',
            field=models.CharField(default=tasks.models.create_task_slug, max_length=32, unique=True),
        ),
    ]
