# Generated by Django 3.0.6 on 2020-05-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200518_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial3afc',
            name='answer',
        ),
        migrations.AddField(
            model_name='response3afc',
            name='answer',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')], null=True),
        ),
    ]
