# Generated by Django 3.0.6 on 2020-05-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200525_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='descr',
            field=models.TextField(default='', help_text='Please provide a one- or two-sentence description', verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='displayname',
            field=models.CharField(default='', help_text='Human-friendly name for the task to be used for display', max_length=80, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.ImageField(help_text='Upload an image that will appear as an icon for this task', upload_to='taskicons/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Short codename for task (no spaces)', max_length=24, primary_key=True, serialize=False, verbose_name='Name'),
        ),
    ]
