# Generated by Django 3.0.6 on 2020-05-18 19:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_auto_20200518_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionNAFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicenum', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='TrialNAFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus', models.URLField()),
                ('answer', models.PositiveSmallIntegerField(null=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='trial3afc',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='tasktype',
            field=models.SmallIntegerField(choices=[(1, 'nAFC'), (2, 'Open-Set')], null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.ImageField(help_text='Upload an image that will appearas an icon for this task on the home page', upload_to='taskicons/'),
        ),
        migrations.DeleteModel(
            name='Response3AFC',
        ),
        migrations.DeleteModel(
            name='Trial3AFC',
        ),
        migrations.AddField(
            model_name='trialnafc',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
