# Generated by Django 3.0.6 on 2020-05-19 04:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_auto_20200518_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trialnum', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('nafcanswer', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('openanswer', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('parenttask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OptionNAFC',
        ),
        migrations.DeleteModel(
            name='TrialNAFC',
        ),
    ]
