# Generated by Django 3.0.6 on 2020-06-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200531_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_url',
            field=models.CharField(default='Xp-_3HXyjtuDzEWWM1fYVKV7fedV8ntb_jn397vU_mU', max_length=32, unique=True),
        ),
    ]
