# Generated by Django 3.0.7 on 2020-06-09 00:17

from django.db import migrations, models
import tasks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200601_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_url',
            field=models.CharField(default='Kj0lFwb5Do3uqxEs_N1xyIKsgeTps--tty0t8CTzGKw', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktype',
            field=models.SmallIntegerField(choices=[(1, 'adaptive'), (2, 'constant-fixed'), (3, 'constant-randomized')], null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='trialinfo',
            field=models.TextField(help_text='Paste the contents of JSON file with task information', validators=[tasks.validators.taskjson_validate], verbose_name='Trial Info'),
        ),
    ]
