# Generated by Django 3.0.7 on 2020-06-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200608_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descr',
            field=models.CharField(default='', help_text='Please provide a one sentence description', max_length=255, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='displayname',
            field=models.CharField(default='', help_text='Experimenter/Subject-friendly title or name for the task', max_length=80, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_url',
            field=models.CharField(default='HtIFPcIlwo1htXV5AiVmjwdLGqQLRLGhNqfY5gkhBsg', max_length=32, unique=True),
        ),
    ]
