# Generated by Django 3.0.7 on 2020-06-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200608_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_url',
            field=models.CharField(default='8oDG_QJRd4t4T6bMh4luFeNlihLmVBWPePyjwlDj8sM', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktype',
            field=models.SmallIntegerField(choices=[(1, 'constant-fixed'), (2, 'constant-randomized')], null=True),
        ),
    ]
