# Generated by Django 3.0.7 on 2020-06-14 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjid', models.CharField(help_text='Enter your ID from Prolific (or) MTurk (or) from SNAPlab', max_length=32, primary_key=True, serialize=False, verbose_name='Participant ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('consented', models.BooleanField(default=False)),
            ],
        ),
    ]
