# Generated by Django 3.0.7 on 2020-07-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectprofile',
            name='parent_study_slug',
            field=models.SlugField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='hl_dur',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of years since you were first given a hearing-loss diagnosis', null=True, verbose_name='If you selected "Yes" to being diagnosed with hearing loss, for how many YEARS have had hearing loss?'),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='hl_subjective',
            field=models.CharField(choices=[('G', 'Is similar to (or) better than others my age'), ('Y', 'I have more trouble than others when there is background noise (e.g., at restaurants, busy streets)'), ('R', 'I have more trouble than others my age in most situations')], help_text='In your own assessment, how do you think your hearing compares to other people your age?', max_length=1, null=True, verbose_name='Hearing Ability'),
        ),
    ]
