# Generated by Django 3.0.7 on 2020-06-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectprofile',
            name='right_handed',
        ),
    ]
