# Generated by Django 3.0.7 on 2020-06-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectprofile',
            name='hl',
            field=models.CharField(choices=[('Y', 'Yes'), ('NO', 'No')], help_text='Choose yes only if formally diagnosed by a certified professional (e.g., Audiologist / ENT)', max_length=2, null=True, verbose_name='Because we study how our ears and brain work together to help us process and interpret sounds, knowing your hearing status will help us interpret your responses more accurately. Have you been diagnosed with hearing loss?'),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='hl_degree',
            field=models.CharField(blank=True, choices=[('MI', 'Mild Hearing Loss'), ('MO', 'Moderate Hearing Loss'), ('SE', 'Severe Hearing Loss'), ('SP', 'Severe-to-Profound Hearing Loss'), ('PR', 'Profound Hearing Loss'), ('UN', 'I Do Not Know'), ('O', 'Other')], default='UN', help_text='If you happen to know your most recent diagnosis, please enter here', max_length=2, verbose_name='If you selected "Yes" to being diagnosed with hearing loss, what is the degree of your hearing loss'),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='hl_dur',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of years since you were first given a hearing-loss diagnosis', null=True, verbose_name='If you selected "Yes" to being diagnosed with hearing loss, How long have you had hearing loss?'),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='hl_subjective',
            field=models.CharField(choices=[('G', 'Is similar to or better than or others my age'), ('Y', 'I have more trouble than others when there is background noise (e.g., at restaurants, busy streets)'), ('R', 'I have more trouble than others my age in most situations')], help_text='In your own assessment, how do you think your hearing compares to other people your age?', max_length=1, null=True, verbose_name='Hearing Ability'),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='hl_write_in',
            field=models.CharField(blank=True, help_text='In your own words, please provide any information', max_length=256, null=True, verbose_name='If you selected "Other" for degree of hearing loss, please provide further information'),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='neuro',
            field=models.CharField(choices=[('Y', 'Yes'), ('NO', 'No')], help_text='Choose yes only if formally diagnosed by a certified professional (e.g., medical doctor)', max_length=2, null=True, verbose_name='Because we study how our ears and brain work together to help us process and interpret sounds, knowing your neurological status will help us interpret your responses more accurately. Have you been diagnosed with a neurological disorder?'),
        ),
    ]
