# Generated by Django 3.0.7 on 2020-07-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200713_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectprofile',
            name='hl_dur',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of years since you were first given a hearing-loss diagnosis', null=True, verbose_name='If you selected "Yes" to being diagnosed with hearing loss, for how many YEARS have you had hearing loss?'),
        ),
    ]
