# Generated by Django 3.0.7 on 2020-06-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200624_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectprofile',
            name='hl',
            field=models.CharField(choices=[('Y', 'Yes'), ('NO', 'No')], help_text='Choose yes only if formally diagnosed by a certified professional (e.g., Audiologist / ENT)', max_length=2, null=True, verbose_name='Have you been diagnosed with hearing loss?'),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='hl_dur',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of years since you were first given a hearing-loss diagnosis', null=True, verbose_name='If you selected "Yes" to being diagnosed with hearing loss, how long would you say you have had hearing loss?'),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='neuro',
            field=models.CharField(choices=[('Y', 'Yes'), ('NO', 'No')], help_text='Choose yes only if formally diagnosed by a certified professional (e.g., medical doctor)', max_length=2, null=True, verbose_name='Have you been diagnosed with a neurological disorder?'),
        ),
    ]
