# Generated by Django 3.0.7 on 2020-06-16 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200616_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subject',
            name='latest_visit',
            field=models.DateTimeField(),
        ),
    ]
