# Generated by Django 3.0.7 on 2020-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200624_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectprofile',
            name='hl_degree',
            field=models.CharField(blank=True, choices=[('MI', 'Mild Hearing Loss'), ('MO', 'Moderate Hearing Loss'), ('SE', 'Severe Hearing Loss'), ('SP', 'Severe-to-Profound Hearing Loss'), ('PR', 'Profound Hearing Loss'), ('UN', 'I Do Not Know'), ('O', 'Other')], help_text='If you happen to know your most recent diagnosis, please enter here', max_length=2, verbose_name='If you selected "Yes" to being diagnosed with hearing loss, what is the degree of your hearing loss'),
        ),
    ]
