# Generated by Django 3.0.7 on 2020-06-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200617_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='latest_consent',
            field=models.DateTimeField(null=True),
        ),
    ]
