# Generated by Django 3.0.7 on 2020-06-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subject_latest_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(help_text='Enter your age in years', null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer Not To Answer')], help_text='Please select your gender', max_length=1)),
                ('enthnicity', models.CharField(choices=[('H', 'Hispanic'), ('NH', 'NOT Hispanic'), ('N', 'Prefer Not To Answer')], help_text='Select the category that best describes you', max_length=2)),
                ('race', models.CharField(choices=[('AM', 'American Indian/Alaskan Native'), ('AS', 'Asian'), ('PI', 'Native Hawaiian or Other Pacific Islander'), ('BL', 'Black or African American'), ('WH', 'White'), ('MR', 'More than one'), ('O', 'Other'), ('N', 'Prefer Not To Answer')], help_text='Select the category that best describes you', max_length=2)),
                ('american_english', models.BooleanField(help_text='For example, did you grow up in the United States/Canada from a young age (< 10 years)?', null=True, verbose_name='Are you a native speaker of North American English?')),
                ('right_handed', models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('B', 'I Use Both Equally')], help_text='Select an option that best describes you', max_length=1, verbose_name='Are you right or left handed?')),
                ('neuro', models.BooleanField(help_text='Choose yes only if formally diagnosed by  medical doctor', verbose_name='Have you been diagnosed with a neurological disorder?')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Subject')),
            ],
        ),
    ]
