# Generated by Django 3.0.7 on 2020-06-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subjectprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectprofile',
            name='neuro',
            field=models.BooleanField(help_text='Choose yes only if formally diagnosed by  medical doctor', null=True, verbose_name='Have you been diagnosed with a neurological disorder?'),
        ),
    ]
