# Generated by Django 3.0.7 on 2020-06-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200618_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectprofile',
            name='hl',
            field=models.CharField(choices=[('Y', 'Yes'), ('NO', 'No')], help_text='Choose yes only if formally diagnosed by a certified professional (e.g., Audiologist / ENT)', max_length=2, null=True, verbose_name='Have you been diagnosed with hearing loss?'),
        ),
        migrations.AddField(
            model_name='subjectprofile',
            name='hl_dur',
            field=models.PositiveSmallIntegerField(help_text='Number of years since you were first given a hearing-loss diagnosis', null=True, verbose_name='How long have you had hearing loss?'),
        ),
        migrations.AddField(
            model_name='subjectprofile',
            name='hl_subjective',
            field=models.CharField(choices=[('G', 'Is as good is better than or similar to others my age'), ('Y', 'I have some trouble when there is background noise (e.g., at restaurants, busy streets)'), ('R', 'I have more trouble than others my age in most situations')], help_text='How do you think your hearing compares to other people your age?', max_length=1, null=True, verbose_name='Hearing Ability'),
        ),
        migrations.AddField(
            model_name='subjectprofile',
            name='hl_type',
            field=models.CharField(default='UN', help_text='If you happen to know you what degree you were diagnosed with, please enter here', max_length=2, verbose_name='Degree of hearing loss'),
        ),
        migrations.AddField(
            model_name='subjectprofile',
            name='hl_write_in',
            field=models.CharField(help_text='If you selected "Other" for degree of hearing loss', max_length=256, null=True, verbose_name='Please write in'),
        ),
        migrations.AddField(
            model_name='subjectprofile',
            name='music',
            field=models.PositiveSmallIntegerField(default=0, help_text='Please count up the years of instrument practice or formal vocal training you have', verbose_name='Years of music training'),
        ),
        migrations.AddField(
            model_name='subjectprofile',
            name='tinnitus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Never'), (1, 'Occasionally (e.g., when it is quiet at night)'), (2, 'Persistently (it is noticeable all the time) but it does NOT bother me'), (3, 'All the time and it is bothersome, but I never sought treatment for it'), (4, 'I have bothersome tinnitus and I tried to get treatment for it')], default=0, help_text='Tinnitus is any ringing/buzzing/hissing/other sounds just in your ear when there is nothing near you that is actually producing the sound', verbose_name='Have you ever experienced tinnitus?'),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, help_text='Enter your age in years'),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='american_english',
            field=models.CharField(choices=[('Y', 'Yes'), ('NO', 'No')], help_text='For example, did you grow up in the United States/Canada from a young age (< 10 years)?', max_length=2, null=True, verbose_name='Are you a native speaker of North American English?'),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='neuro',
            field=models.CharField(choices=[('Y', 'Yes'), ('NO', 'No')], help_text='Choose yes only if formally diagnosed by a certified professional (e.g., medical doctor)', max_length=2, null=True, verbose_name='Have you been diagnosed with a neurological disorder?'),
        ),
    ]
