# Generated by Django 3.0.7 on 2020-06-18 18:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200618_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectprofile',
            name='age',
            field=models.PositiveSmallIntegerField(help_text='Enter your age in years', null=True, validators=[users.models.adults_only]),
        ),
    ]
