# Generated by Django 3.0.7 on 2020-07-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studytree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknode',
            name='pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Compensation (US$)'),
        ),
    ]
