# Generated by Django 3.0.7 on 2020-07-04 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studytree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyroot',
            name='experimenter',
        ),
        migrations.AddField(
            model_name='basenode',
            name='experimenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyroot',
            name='displayname',
            field=models.CharField(default='SNAPlab Hearing Study', help_text='Experimenter/Subject-friendly title or name for the study', max_length=80, verbose_name='Display Name'),
        ),
    ]
