# Generated by Django 3.0.7 on 2020-07-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studytree', '0002_tasknode_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroot',
            name='addcoresurvey',
            field=models.BooleanField(blank=True, default=False, help_text='Check the box to add our core survey as the first item in the study', verbose_name='Add core survey to study?'),
        ),
    ]
