# Generated by Django 3.0.7 on 2020-06-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jspsych', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletrialresponse',
            name='trialnum',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
