# Generated by Django 3.0.7 on 2020-06-14 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jspsych', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjid', models.CharField(help_text='Enter your ID from Prolific (or) MTurk (or) from SNAPlab', max_length=32, primary_key=True, serialize=False, verbose_name='Participant ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('consented', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SNAPlab Study', help_text='Short title for study', max_length=24)),
                ('welcome_message', models.TextField(default='', help_text='A welcome screen message suitable for display in the landing page for your subjects')),
                ('study_url', models.CharField(max_length=32, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('experimenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task1_set', to='jspsych.Jstask')),
                ('task2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task2_set', to='jspsych.Jstask')),
            ],
        ),
        migrations.AddField(
            model_name='oneshotresponse',
            name='parent_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jspsych.Study'),
        ),
        migrations.AddField(
            model_name='oneshotresponse',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jspsych.Subject'),
        ),
        migrations.AddField(
            model_name='singletrialresponse',
            name='parent_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jspsych.Study'),
        ),
        migrations.AddField(
            model_name='singletrialresponse',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jspsych.Subject'),
        ),
    ]
