# Generated by Django 3.0.7 on 2020-06-23 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jspsych', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveTask',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jspsych.BaseTask')),
                ('tasksinfo', models.TextField(help_text='Paste the contents of JSON file for adaptive n-AFC task', verbose_name='Task Details')),
            ],
            bases=('jspsych.basetask',),
        ),
        migrations.CreateModel(
            name='OpenSpeechTask',
            fields=[
                ('basetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jspsych.BaseTask')),
                ('tasksinfo', models.TextField(help_text='Paste the contents of JSON file for adaptive 3-AFC task', verbose_name='Task Details')),
            ],
            bases=('jspsych.basetask',),
        ),
        migrations.RenameModel(
            old_name='Jstask',
            new_name='ConstStimTask',
        ),
        migrations.RenameModel(
            old_name='Jsrawtask',
            new_name='RawTask',
        ),
        migrations.AddField(
            model_name='basetask',
            name='task_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Constant Stimulus n-AFC'), (2, 'Raw Script'), (3, 'Adaptive n-AFC'), (4, 'Open-set Speech')], default=1),
        ),
        migrations.AddField(
            model_name='study',
            name='task10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task10_set', to='jspsych.BaseTask'),
        ),
        migrations.AddField(
            model_name='study',
            name='task11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task11_set', to='jspsych.BaseTask'),
        ),
        migrations.AddField(
            model_name='study',
            name='task12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task12_set', to='jspsych.BaseTask'),
        ),
        migrations.AddField(
            model_name='study',
            name='task3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task3_set', to='jspsych.BaseTask'),
        ),
        migrations.AddField(
            model_name='study',
            name='task4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task4_set', to='jspsych.BaseTask'),
        ),
        migrations.AddField(
            model_name='study',
            name='task5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task5_set', to='jspsych.BaseTask'),
        ),
        migrations.AddField(
            model_name='study',
            name='task6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task6_set', to='jspsych.BaseTask'),
        ),
        migrations.AddField(
            model_name='study',
            name='task7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task7_set', to='jspsych.BaseTask'),
        ),
        migrations.AddField(
            model_name='study',
            name='task8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task8_set', to='jspsych.BaseTask'),
        ),
        migrations.AddField(
            model_name='study',
            name='task9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task9_set', to='jspsych.BaseTask'),
        ),
        migrations.AlterField(
            model_name='oneshotresponse',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jspsych.BaseTask'),
        ),
        migrations.AlterField(
            model_name='singletrialresponse',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jspsych.BaseTask'),
        ),
        migrations.AlterField(
            model_name='study',
            name='task1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task1_set', to='jspsych.BaseTask'),
        ),
        migrations.AlterField(
            model_name='study',
            name='task2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_task2_set', to='jspsych.BaseTask'),
        ),
    ]
