# Generated by Django 3.0.7 on 2020-06-22 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jspsych.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jspsych', '0002_auto_20200621_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jstask',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='jstask',
            name='tasktype',
        ),
        migrations.CreateModel(
            name='Jsrawtask',
            fields=[
                ('name', models.CharField(help_text='Short codename for task (no spaces)', max_length=24, primary_key=True, serialize=False, verbose_name='Name')),
                ('displayname', models.CharField(default='', help_text='Experimenter/Subject-friendly title or name for the task', max_length=80, verbose_name='Display Name')),
                ('descr', models.CharField(default='', help_text='Please provide a one sentence description', max_length=255, verbose_name='Short description')),
                ('taskscript', models.TextField(help_text='Paste the jsPsych code here, just the javascript part', validators=[jspsych.validators.taskjson_validate], verbose_name='Task Script')),
                ('task_url', models.SlugField(max_length=32, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('experimenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
